name: Deploy to DGSL Server
on:
  workflow_run:
    workflows: ["Build & PHPCS project"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 10.254.6.92
        username: dgsl
        password: undpdgsl143
        port: 22
        script: whoami
