name: Deploy to DGSL Server
on:
  workflow_run:
    workflows: ["Build & PHPCS project"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to droplet using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        debug: true
        script: |
          cd ${{ secrets.DOCROOT }}
          git pull
          robo job:drupal-update
